# Generated by Django 5.0.3 on 2024-04-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payment_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
